### ISSUE TITLE
Downloadhandler doesnt respect the paste function.

### ISSUE THREAD

**Issue by davidrajm** [aagarw30/R-Shinyapp-Tutorial#2]
My ur.R file goes as follows:

```
library(shiny)


shinyUI(
  fluidPage(
    titlePanel(title = h4('Demonstraion of renderplot', align='center')),
    sidebarLayout(
      sidebarPanel(
        selectInput('var', "Select the Variable", choices = c('Sepal.Length' =1 , 'sepal width' = 2, 'Petal Length' = 3 , 'Petal Width' = 4), selected = 1),
        br(),
        sliderInput('bins', 'Select the number of bins', min = 5, max = 25, value = 15),
        br(),
        radioButtons('color', 'Color of the bins', choices = c('Green', 'Red', 'Blue'), selected = 'Green'),
        br(),
        radioButtons('type', 'Choose the type', choices = list('png', 'pdf'), selected = 'png')
        
      ),
    mainPanel(
      plotOutput("myhist"),
      downloadButton('down', 'Download the Plot')
      
      
    )
    )
  )
)
```
and my server.R goes as follows:
```library(shiny)

shinyServer(function(input, output){
  
  colm = reactive({
    as.numeric(input$var)
  }) 
  output$myhist = renderPlot(
    {
      hist(iris[,colm()], breaks = seq(0,max(iris[,colm()], l= input$bins+1)),col =input$color, main ="Histogram of irish dataset", xlab = names(iris[colm()]))
    }
  )
  
  output$down <- downloadHandler(
    filename =  function() {
      paste("iris", input$var3, sep=".")
    },
    # content is a function with argument file. content writes the plot to the device
    content = function(file) {
      if(input$var3 == "png")
        png(file) # open the png device
      else
        pdf(file) # open the pdf device
      hist(colm()) # draw the plot
      dev.off()  # turn the device off
      
    } 
  )
  
  
  
}) 
```

![image](https://user-images.githubusercontent.com/15086149/39674175-794a6176-5165-11e8-9772-cce492aafd33.png)

When I hit the download button, It shows like the following whereas the file name suppose to be `iris.png`. Why this behaviour?
![image](https://user-images.githubusercontent.com/15086149/39674186-a85d75b6-5165-11e8-9100-bd756d2b43fd.png)

I have also tried wrapping arguments of the function, `downdloadHandler` like this
```
output$down <- downloadHandler({
    filename =  function() {
      paste("iris", input$var3, sep=".")
    },
    # content is a function with argument file. content writes the plot to the device
    content = function(file) {
      if(input$var3 == "png")
        png(file) # open the png device
      else
        pdf(file) # open the pdf device
      hist(colm()) # draw the plot
      dev.off()  # turn the device off
      
    } 
  })
```

But this gave the error message as follows. 

```
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  G:\R_workshop_related_NITTE\Shiny\downloadPlots/server.R:17:6: unexpected ','
16:       paste("iris", input$var3, sep=".")
17:     },
         ^
Warning: Error in sourceUTF8: Error sourcing C:\Users\Mahe\AppData\Local\Temp\RtmpIPEtpl\file29805c1e4eca
Stack trace (innermost first):
    1: runApp
Error in sourceUTF8(serverR, envir = new.env(parent = globalenv())) : 
  Error sourcing C:\Users\Mahe\AppData\Local\Temp\RtmpIPEtpl\file29805c1e4eca
```
I am in windows machine Rstudio Version 1.1.442 with R 3.4.4.

**Comment by aagarw30** [comment]
Hello David,
Thanks for the details.

Sharing the observation -
Not sure why you have input$var3 in your downloadhandler(). The UI does not have any input widget with var3 input ID.

Nevertheless, I ran the code with the following updates -
 output$down <- downloadHandler(
    filename =  function() {
      paste("iris", input$type, sep=".") **# replace input$var3 by input$type ty Abi**
    },
    # content is a function with argument file. content writes the plot to the device
    content = function(file) {
      if(input$type == "png") **# replace input$var3 by input$type ty Abi**
        png(file) # open the png device
      else
        pdf(file) # open the pdf device
      hist(colm()) # draw the plot
      dev.off()  # turn the device off
      
    } 
  )

Code ran without any errors.

Important Point to note -
I am guessing that you are running the app in the window. This would be the "Run in Window" option of the "Run App" icon in the RStudio. If so, then for some reason RStudio would pop up the dialog box ignoring the file name you create using paste and would show the file name as the output ID of download handler which in your case is "down". It is a known behavior.

I suggest you choose "Run External" and then you should be able to download the file with the file name you have defined in the downloadhandler function. I have tested it and should work for you. Let me know how it goes.

I will exclusively make a video as well to show this to you tube viewers so it is easy to understand and they do not take this as a failure on them or an issue per say. 

I will wait for your response so can close this item.

Thanks, have a great day!

Regards,
Abi

**Comment by davidrajm** [comment]
Thank you so much for  identifying the error in the variable.

` I am guessing that you are running the app in the window. `
You are amazing. I was running the app in the window. Now when I run in the
external, it does the job.

I
​ also have replaced the line `hist(colm())` with

hist(iris[,colm()], breaks = seq(0,max(iris[,colm()], l= input$bins+1)),col
=input$color, main ="Histogram of irish dataset", xlab =
names(iris[colm()]))

which gave me the plot as requied, otherwise I was getting only the empty
plot.

Thank you for the help.
​

Thanks & regards,

*David Raj Micheal*

Research Scholar,
Department of Statistics, PSPH, MAHE, Manipal.
Mobile: 0 75028 78908
Office : 0820 2922407

**Comment by aagarw30** [comment]
Youtube video from my channel reproducing and explaining the behavior of download plot
https://youtu.be/a6UOnYejni8
