### ISSUE TITLE
Need help on Submit button

### ISSUE THREAD

**Issue by samdhu1116** [aagarw30/R-Shinyapp-Tutorial#4]
I was going through your video on "Submit Button"  - Example 2.

It is very helpful. 

Thanks,
Madhuri

**Comment by aagarw30** [comment]
Hello Madhuri,
Sure, I will check it out.
Also will help you.
Right now I am in office work hours. Will get back to you soon.
Ty
Abi.

**Comment by aagarw30** [comment]
Hello Madhuri,
I did check the code and tested and it is functioning properly without any issues.
Code is available at the below link for reference:

https://github.com/aagarw30/R-Shinyapp-Tutorial/tree/master/submitButton%20Example2

Sorry, not able to understand what is missing in the code?

Let me know.

ty Abhinav

**Comment by samdhu1116** [comment]
Hi Abhinav,

I recheked again on the code. I have miss understood the code.

Initially, we do not need to press submit button as we have defined the
Iris dataset as default. We need to use the update button only when we
choose a different dataset.

I missed understood the code at first. Now, i am clear.

Apologies for the inconvenience caused by me.


Thanks,
Madhuri

**Comment by aagarw30** [comment]
Thanks Madhuri
I will close the ticket.

Ty
Abi.

**Comment by samdhu1116** [comment]
Hi Abhinav,

I need some help on R shiny and i am stuck in this.

How to update choices of SelectInput dynamically?
 I mean i have 3 drop downs
If the user selects an option in 1st drop down then the 2nd drop down
should dynamically show inputs related to the choice made
and like wise for the 3rd drop down will have list of values dependent on 1
and 2nd input chosen

Please share an example if you have.

Thanks,
Madhuri

**Comment by aagarw30** [comment]
Hello Madhuri,
updateselectInput() will help you.
See an example here from one of my gist and this might help you...

https://gist.github.com/aagarw30/d08c5fb1794cf9b58fa38342db97b697

**Comment by samdhu1116** [comment]
Sure. I will check it out.

Thanks,
Madhuri

**Comment by samdhu1116** [comment]
Hi Abhinav,

Greetings!

Hope you are doing well.

I was exploring something in R Shiny basis your example code of fileInput.

Request for help.

I have now read the file using fileInput, post this i need to do header
cleaning and some data cleaning before i proceed further in the application.

Now i tried doing the that using the reactive function but it throws an
error message as
"Evaluation nested too deeply: infinite recursion/options(expressions=)?

Can you please help me here?

Thanks,
Madhuri
